export const Roles = {
  ASSISTANT: 'ASSISTANT',
  ASSISTANT_SURGICAL: 'ASSISTANT_SURGICAL',
  ASSISTANT_VIRTUAL: 'ASSISTANT_VIRTUAL',
  SPEAKER: 'SPEAKER',
  COMMITTEE: 'COMMITTEE',
  STAFF: 'STAFF',
  SPONSOR: 'SPONSOR',
  ADMIN: 'ADMIN'
} as const;

export type Role = keyof typeof Roles;
